#! /bin/bash

echo "********** PATH SCRIPT **********"

old_IFS=$IFS;
IFS=":";


# CHECKING IF COMMAND IS PRESENT IN PATH
if [ $1 == "-c" ];
then
    my_com="$2";
    for dir in $PATH; 
    do
        if [ -e "$dir/$my_com" ]; 
        then
            echo "**********COMMAND PRESENT IN PATH**********"
            echo "$dir/$my_com" 
        fi
    done

# CHECKING IF DIRECTORY IS PRESENT IN PATH
elif [ $1 == "-d" ];
then 
    my_dir="$2";
    for dir in $PATH;
    do
        if [ $my_dir == $dir -o $my_dir == "$dir/" ]; 
        then
            echo "**********FOUND**********"
        fi
    done

# CLEAN LIST OF PATH 
else 
    for dir in $PATH; 
    do
        echo "$dir"
    done
fi



IFS=$old_IFS